# Use a specific version of Node.js
FROM node:18.17.1


# Set the working directory inside the container
WORKDIR /app


COPY package.json ./


# Install dependencies
RUN npm install --no-package-lock


# Copy the entire project into the container
COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]




