# Use a specific version of Node.js
FROM node:18.17.1

# Set the working directory inside the container
WORKDIR /app

# Copy the entire project into the container
COPY . .

# Install dependencies
RUN npm install

# Set working directory to frontend
WORKDIR /app/frontend

# Expose the frontend port
EXPOSE 5173

# Start the frontend server
CMD ["npm", "run", "dev", "--", "--host"]

